[tool.poetry]
name = "polytune"
version = "0.1.0"
description = ""
authors = ["Konstantin Templin <1qnbhd@gmail.com>"]

[tool.poetry.dependencies]
python = "3.9.9"
scipy = "^1.8.0"
click = "^8.0.3"
numpy = "^1.22.2"
scikit-optimize = "^0.9.0"
rich = "^11.2.0"
pandas = "^1.4.0"
executor = "^23.2"

[tool.poetry.dev-dependencies]
pytest = "^7.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
