[tool.poetry]
name = "polytune"
version = "0.1.0"
description = ""
authors = ["Konstantin Templin <1qnbhd@gmail.com>"]

[tool.poetry.dependencies]
python = "3.9.9"
scipy = "^1.8.0"
click = "^8.0.3"
numpy = "^1.22.2"
scikit-optimize = "^0.9.0"
rich = "^11.2.0"
pandas = "^1.4.0"
executor = "^23.2"
eff = "^1.0.0"
pydantic = "^1.9.0"
tinydb = "^4.6.1"
jupyter = "^1.0.0"
multiprocess = "^0.70.12"

[tool.poetry.dev-dependencies]
pytest = "^7.0.0"
mypy = "^0.931"
types-PyYAML = "^6.0.4"
pydeps = "^1.10.12"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
