[tool.poetry]
name = "gimeltune"
version = "0.1.0"
description = "Hyperparameter's optimization framework"
authors = ["Konstantin Templin <1qnbhd@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
scipy = "^1.8.0"
click = "^8.1.2"
scikit-optimize = "^0.9.0"
rich = "^12.2.0"
executor = "^23.2"
pydantic = "^1.9.0"
tinydb = "^4.7.0"
multiprocess = "^0.70.12"
numpy = "^1.22.3"
pandas = "^1.4.2"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
isort = "^5.10.1"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
